on: 
  push:
    branches: 
      - main
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  new_job: 
    runs-on: self-hosted
    name: test 
    steps:
      - name: 1 test
        run: echo "Hello from the variable " ${{ vars.ALFREDO_VAR }}
  new_job_dev: 
    runs-on: self-hosted
    environment: DEV
    name: test 
    steps:
      - name: 1 test
        run: echo "Hello from the variable " ${{ vars.ALFREDO_VAR }}
  create-cluster:
    runs-on: self-hosted
    needs: new_job
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with: 
          cluster_name: test-alfredo-local
          config: ./kind/install.yml
      - name: Deploy Manifest
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kube/
  kind_cluster_local:
    runs-on: self-hosted
    name: Run a manifest on a local k8s cluster
    needs: new_job
    env:
      KUBE_CONFIG: ${{ secrets.KIND_KUBE_CLUSTER}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Manifest
        uses: actions-hub/kubectl@master
        with:
#          args: get node
          args: apply -f kube/
